markdown: kramdown
kramdown:
  parse_block_html: true
safe: true
lsi: false
highlither: pygments
port: 7000
title : broderson.org
exclude:
 - CNAME
 - .gitignore
 - _config.yml
 - Gemfile
post:
  template: _template_post.txt
  extension: md
editor: vim
plugins:
 - jemoji
 - jekyll-sitemap
collections:
  topics:
    output: true
    layout: default
